pipeline {
  agent any

  environment {
    PROJECT_ID = "gcp-cicd-demo-480118"
    TF_IN_AUTOMATION = "true"
  }

  stages {

    stage('Checkout') {
      steps {
        checkout scm
      }
    }

    /*stage('Authenticate to GCP') {
      steps {
        withCredentials([file(credentialsId: 'gcp-service-account-key', variable: 'GOOGLE_APPLICATION_CREDENTIALS')]) {
          sh '''
            gcloud auth activate-service-account --key-file=$GOOGLE_APPLICATION_CREDENTIALS
            gcloud config set project $PROJECT_ID
          '''
        }
      }
    }*/

    stage('Terraform Init') {
      steps {
        dir('cloudnotes-infra') {
          sh 'terraform init'
        }
      }
    }

    stage('Terraform Validate') {
      steps {
        dir('cloudnotes-infra') {
          sh '''
            terraform fmt -recursive
            terraform validate
          '''
        }
      }
    }

    stage('Terraform Plan') {
      steps {
        dir('cloudnotes-infra') {
          sh 'terraform plan -out=tfplan'
        }
      }
    }

    stage('Approval') {
      steps {
        input message: 'Approve Terraform Apply?'
      }
    }

    stage('Terraform Apply') {
      steps {
        dir('cloudnotes-infra') {
          sh 'terraform apply -auto-approve tfplan'
        }
      }
    }
  }

  post {
    always {
      archiveArtifacts artifacts: 'cloudnotes-infra/tfplan', fingerprint: true
    }
  }
}
